# Copyright The Kubeflow Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# coding: utf-8

"""
    Kubeflow Trainer OpenAPI Spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: unversioned
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from kubeflow_trainer_api.models.io_k8s_api_scheduling_v1alpha3_composite_pod_group_template import IoK8sApiSchedulingV1alpha3CompositePodGroupTemplate
from kubeflow_trainer_api.models.io_k8s_api_scheduling_v1alpha3_pod_group_template import IoK8sApiSchedulingV1alpha3PodGroupTemplate
from kubeflow_trainer_api.models.io_k8s_api_scheduling_v1alpha3_typed_local_object_reference import IoK8sApiSchedulingV1alpha3TypedLocalObjectReference
from typing import Optional, Set
from typing_extensions import Self

class IoK8sApiSchedulingV1alpha3WorkloadSpec(BaseModel):
    """
    WorkloadSpec defines the desired state of a Workload.
    """ # noqa: E501
    composite_pod_group_templates: Optional[List[IoK8sApiSchedulingV1alpha3CompositePodGroupTemplate]] = Field(default=None, description="compositePodGroupTemplates is the list of CompositePodGroup templates that make up the Workload. The maximum number of templates is 8. This field is immutable. Exactly one of CompositePodGroupTemplates and PodGroupTemplates must be set.  This field is used only when the CompositePodGroup feature gate is enabled.", alias="compositePodGroupTemplates")
    controller_ref: Optional[IoK8sApiSchedulingV1alpha3TypedLocalObjectReference] = Field(default=None, description="controllerRef is an optional reference to the controlling object, such as a Deployment or Job. This field is intended for use by tools like CLIs to provide a link back to the original workload definition. This field is immutable.", alias="controllerRef")
    pod_group_templates: Optional[List[IoK8sApiSchedulingV1alpha3PodGroupTemplate]] = Field(default=None, description="podGroupTemplates is the list of templates that make up the Workload. The maximum number of templates is 8. Templates cannot be added or removed after the workload is created. Existing templates may still be updated where their individual fields allow it. Exactly one of CompositePodGroupTemplates and PodGroupTemplates must be set.", alias="podGroupTemplates")
    __properties: ClassVar[List[str]] = ["compositePodGroupTemplates", "controllerRef", "podGroupTemplates"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IoK8sApiSchedulingV1alpha3WorkloadSpec from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in composite_pod_group_templates (list)
        _items = []
        if self.composite_pod_group_templates:
            for _item_composite_pod_group_templates in self.composite_pod_group_templates:
                if _item_composite_pod_group_templates:
                    _items.append(_item_composite_pod_group_templates.to_dict())
            _dict['compositePodGroupTemplates'] = _items
        # override the default output from pydantic by calling `to_dict()` of controller_ref
        if self.controller_ref:
            _dict['controllerRef'] = self.controller_ref.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in pod_group_templates (list)
        _items = []
        if self.pod_group_templates:
            for _item_pod_group_templates in self.pod_group_templates:
                if _item_pod_group_templates:
                    _items.append(_item_pod_group_templates.to_dict())
            _dict['podGroupTemplates'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IoK8sApiSchedulingV1alpha3WorkloadSpec from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "compositePodGroupTemplates": [IoK8sApiSchedulingV1alpha3CompositePodGroupTemplate.from_dict(_item) for _item in obj["compositePodGroupTemplates"]] if obj.get("compositePodGroupTemplates") is not None else None,
            "controllerRef": IoK8sApiSchedulingV1alpha3TypedLocalObjectReference.from_dict(obj["controllerRef"]) if obj.get("controllerRef") is not None else None,
            "podGroupTemplates": [IoK8sApiSchedulingV1alpha3PodGroupTemplate.from_dict(_item) for _item in obj["podGroupTemplates"]] if obj.get("podGroupTemplates") is not None else None
        })
        return _obj


