# Copyright The Kubeflow Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# coding: utf-8

"""
    Kubeflow Trainer OpenAPI Spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: unversioned
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from kubeflow_trainer_api.models.io_k8s_api_scheduling_v1alpha3_workload_pod_group_disruption_mode import IoK8sApiSchedulingV1alpha3WorkloadPodGroupDisruptionMode
from kubeflow_trainer_api.models.io_k8s_api_scheduling_v1alpha3_workload_pod_group_resource_claim import IoK8sApiSchedulingV1alpha3WorkloadPodGroupResourceClaim
from kubeflow_trainer_api.models.io_k8s_api_scheduling_v1alpha3_workload_pod_group_scheduling_constraints import IoK8sApiSchedulingV1alpha3WorkloadPodGroupSchedulingConstraints
from kubeflow_trainer_api.models.io_k8s_api_scheduling_v1alpha3_workload_pod_group_scheduling_policy import IoK8sApiSchedulingV1alpha3WorkloadPodGroupSchedulingPolicy
from typing import Optional, Set
from typing_extensions import Self

class IoK8sApiBatchV1JobSchedulingConfiguration(BaseModel):
    """
    JobSchedulingConfiguration composes the reusable workload-aware scheduling building blocks.
    """ # noqa: E501
    disruption_mode: Optional[IoK8sApiSchedulingV1alpha3WorkloadPodGroupDisruptionMode] = Field(default=None, description="DisruptionMode defines the mode in which the Job's pods can be disrupted. One of Single, All. This field is immutable after creation: it may not be added or removed, and the selected mode may not be changed.", alias="disruptionMode")
    resource_claims: Optional[List[IoK8sApiSchedulingV1alpha3WorkloadPodGroupResourceClaim]] = Field(default=None, description="ResourceClaims defines which ResourceClaims may be shared among Pods in the Job. Pods consume the devices allocated to a PodGroup's claim by defining a claim in its own Spec.ResourceClaims that matches the PodGroup's claim exactly. The claim must have the same name and refer to the same ResourceClaim or ResourceClaimTemplate. At most 4 claims may be set, matching the limit on the resulting PodGroup. This list is immutable after creation: entries may neither be added, removed, nor modified.", alias="resourceClaims")
    scheduling_constraints: Optional[IoK8sApiSchedulingV1alpha3WorkloadPodGroupSchedulingConstraints] = Field(default=None, description="SchedulingConstraints defines scheduling constraints (e.g. topology) for the Job's pods. This field is immutable after creation.", alias="schedulingConstraints")
    scheduling_policy: Optional[IoK8sApiSchedulingV1alpha3WorkloadPodGroupSchedulingPolicy] = Field(default=None, description="SchedulingPolicy defines the scheduling policy for this Job. Exactly one of Basic or Gang must be set. This field is immutable after creation: the policy may not be added or removed. The policy variant (basic/gang) is frozen by hand-written validation; only schedulingPolicy.gang.minCount may be changed.", alias="schedulingPolicy")
    __properties: ClassVar[List[str]] = ["disruptionMode", "resourceClaims", "schedulingConstraints", "schedulingPolicy"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IoK8sApiBatchV1JobSchedulingConfiguration from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of disruption_mode
        if self.disruption_mode:
            _dict['disruptionMode'] = self.disruption_mode.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in resource_claims (list)
        _items = []
        if self.resource_claims:
            for _item_resource_claims in self.resource_claims:
                if _item_resource_claims:
                    _items.append(_item_resource_claims.to_dict())
            _dict['resourceClaims'] = _items
        # override the default output from pydantic by calling `to_dict()` of scheduling_constraints
        if self.scheduling_constraints:
            _dict['schedulingConstraints'] = self.scheduling_constraints.to_dict()
        # override the default output from pydantic by calling `to_dict()` of scheduling_policy
        if self.scheduling_policy:
            _dict['schedulingPolicy'] = self.scheduling_policy.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IoK8sApiBatchV1JobSchedulingConfiguration from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "disruptionMode": IoK8sApiSchedulingV1alpha3WorkloadPodGroupDisruptionMode.from_dict(obj["disruptionMode"]) if obj.get("disruptionMode") is not None else None,
            "resourceClaims": [IoK8sApiSchedulingV1alpha3WorkloadPodGroupResourceClaim.from_dict(_item) for _item in obj["resourceClaims"]] if obj.get("resourceClaims") is not None else None,
            "schedulingConstraints": IoK8sApiSchedulingV1alpha3WorkloadPodGroupSchedulingConstraints.from_dict(obj["schedulingConstraints"]) if obj.get("schedulingConstraints") is not None else None,
            "schedulingPolicy": IoK8sApiSchedulingV1alpha3WorkloadPodGroupSchedulingPolicy.from_dict(obj["schedulingPolicy"]) if obj.get("schedulingPolicy") is not None else None
        })
        return _obj


