# Copyright The Kubeflow Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# coding: utf-8

"""
    Kubeflow Trainer OpenAPI Spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: unversioned
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from kubeflow_trainer_api.models.io_k8s_api_scheduling_v1alpha3_disruption_mode import IoK8sApiSchedulingV1alpha3DisruptionMode
from kubeflow_trainer_api.models.io_k8s_api_scheduling_v1alpha3_pod_group_resource_claim import IoK8sApiSchedulingV1alpha3PodGroupResourceClaim
from kubeflow_trainer_api.models.io_k8s_api_scheduling_v1alpha3_pod_group_scheduling_constraints import IoK8sApiSchedulingV1alpha3PodGroupSchedulingConstraints
from kubeflow_trainer_api.models.io_k8s_api_scheduling_v1alpha3_pod_group_scheduling_policy import IoK8sApiSchedulingV1alpha3PodGroupSchedulingPolicy
from typing import Optional, Set
from typing_extensions import Self

class IoK8sApiSchedulingV1alpha3PodGroupTemplate(BaseModel):
    """
    PodGroupTemplate represents a template for a set of pods with a scheduling policy.
    """ # noqa: E501
    disruption_mode: Optional[IoK8sApiSchedulingV1alpha3DisruptionMode] = Field(default=None, description="disruptionMode defines the mode in which a given PodGroup can be disrupted. One of Single, All. This field is immutable.", alias="disruptionMode")
    name: StrictStr = Field(description="name is a unique identifier for the PodGroupTemplate within the Workload. It must be a DNS label. This field is immutable.")
    preemption_policy: Optional[StrictStr] = Field(default=None, description="preemptionPolicy is the Policy for preempting pods/podgroups with lower priority. One of Never, PreemptLowerPriority. This field is immutable. This field is available only when the PodGroupPreemptionPolicy feature gate is enabled.   Possible enum values:  - `\"Never\"` means that pod never preempts other pods with lower priority.  - `\"PreemptLowerPriority\"` means that pod can preempt other pods with lower priority.", alias="preemptionPolicy")
    priority: Optional[StrictInt] = Field(default=None, description="priority is the value of priority of pod groups created from this template. Various system components use this field to find the priority of the pod group. The higher the value, the higher the priority. This field is immutable.")
    priority_class_name: Optional[StrictStr] = Field(default=None, description="priorityClassName indicates the priority that should be considered when scheduling a pod group created from this template. This field is immutable.", alias="priorityClassName")
    resource_claims: Optional[List[IoK8sApiSchedulingV1alpha3PodGroupResourceClaim]] = Field(default=None, description="resourceClaims defines which ResourceClaims may be shared among Pods in the group. Pods consume the devices allocated to a PodGroup's claim by defining a claim in its own Spec.ResourceClaims that matches the PodGroup's claim exactly. The claim must have the same name and refer to the same ResourceClaim or ResourceClaimTemplate.  This is a beta-level field and requires that the DRAWorkloadResourceClaims feature gate is enabled.  This field is immutable.", alias="resourceClaims")
    scheduling_constraints: Optional[IoK8sApiSchedulingV1alpha3PodGroupSchedulingConstraints] = Field(default=None, description="schedulingConstraints defines optional scheduling constraints (e.g. topology) for this PodGroupTemplate. This field is only available when the TopologyAwareWorkloadScheduling feature gate is enabled. This field is immutable.", alias="schedulingConstraints")
    scheduling_policy: IoK8sApiSchedulingV1alpha3PodGroupSchedulingPolicy = Field(description="schedulingPolicy defines the scheduling policy for this PodGroupTemplate.", alias="schedulingPolicy")
    __properties: ClassVar[List[str]] = ["disruptionMode", "name", "preemptionPolicy", "priority", "priorityClassName", "resourceClaims", "schedulingConstraints", "schedulingPolicy"]

    @field_validator('preemption_policy')
    def preemption_policy_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Never', 'PreemptLowerPriority']):
            raise ValueError("must be one of enum values ('Never', 'PreemptLowerPriority')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IoK8sApiSchedulingV1alpha3PodGroupTemplate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of disruption_mode
        if self.disruption_mode:
            _dict['disruptionMode'] = self.disruption_mode.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in resource_claims (list)
        _items = []
        if self.resource_claims:
            for _item_resource_claims in self.resource_claims:
                if _item_resource_claims:
                    _items.append(_item_resource_claims.to_dict())
            _dict['resourceClaims'] = _items
        # override the default output from pydantic by calling `to_dict()` of scheduling_constraints
        if self.scheduling_constraints:
            _dict['schedulingConstraints'] = self.scheduling_constraints.to_dict()
        # override the default output from pydantic by calling `to_dict()` of scheduling_policy
        if self.scheduling_policy:
            _dict['schedulingPolicy'] = self.scheduling_policy.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IoK8sApiSchedulingV1alpha3PodGroupTemplate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "disruptionMode": IoK8sApiSchedulingV1alpha3DisruptionMode.from_dict(obj["disruptionMode"]) if obj.get("disruptionMode") is not None else None,
            "name": obj.get("name") if obj.get("name") is not None else '',
            "preemptionPolicy": obj.get("preemptionPolicy"),
            "priority": obj.get("priority"),
            "priorityClassName": obj.get("priorityClassName"),
            "resourceClaims": [IoK8sApiSchedulingV1alpha3PodGroupResourceClaim.from_dict(_item) for _item in obj["resourceClaims"]] if obj.get("resourceClaims") is not None else None,
            "schedulingConstraints": IoK8sApiSchedulingV1alpha3PodGroupSchedulingConstraints.from_dict(obj["schedulingConstraints"]) if obj.get("schedulingConstraints") is not None else None,
            "schedulingPolicy": IoK8sApiSchedulingV1alpha3PodGroupSchedulingPolicy.from_dict(obj["schedulingPolicy"]) if obj.get("schedulingPolicy") is not None else None
        })
        return _obj


