# Copyright The Kubeflow Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# coding: utf-8

"""
    Kubeflow Trainer OpenAPI Spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: unversioned
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from kubeflow_trainer_api.models.io_k8s_api_scheduling_v1alpha3_composite_disruption_mode import IoK8sApiSchedulingV1alpha3CompositeDisruptionMode
from kubeflow_trainer_api.models.io_k8s_api_scheduling_v1alpha3_composite_pod_group_scheduling_constraints import IoK8sApiSchedulingV1alpha3CompositePodGroupSchedulingConstraints
from kubeflow_trainer_api.models.io_k8s_api_scheduling_v1alpha3_composite_pod_group_scheduling_policy import IoK8sApiSchedulingV1alpha3CompositePodGroupSchedulingPolicy
from kubeflow_trainer_api.models.io_k8s_api_scheduling_v1alpha3_workload_reference import IoK8sApiSchedulingV1alpha3WorkloadReference
from typing import Optional, Set
from typing_extensions import Self

class IoK8sApiSchedulingV1alpha3CompositePodGroupSpec(BaseModel):
    """
    CompositePodGroupSpec defines the desired state of CompositePodGroup.
    """ # noqa: E501
    disruption_mode: Optional[IoK8sApiSchedulingV1alpha3CompositeDisruptionMode] = Field(default=None, description="disruptionMode defines the mode in which a given CompositePodGroup can be disrupted. Controllers are expected to fill this field by copying it from a CompositePodGroupTemplate. One of Single, All. Defaults to Single if unset. This field is immutable.", alias="disruptionMode")
    parent_composite_pod_group_name: Optional[StrictStr] = Field(default=None, description="parentCompositePodGroupName contains the name of the parent composite pod group within the same namespace as this composite pod group. It must be a DNS name. If it's nil, then this composite pod group is a root of a workload's hierarchy. This field is immutable.", alias="parentCompositePodGroupName")
    preemption_policy: Optional[StrictStr] = Field(default=None, description="preemptionPolicy is the Policy for preempting pods/podgroups with lower priority. One of Never, PreemptLowerPriority. Defaults to PreemptLowerPriority if unset. When Priority Admission Controller is enabled, it populates this field from PriorityClassName, and defaults to PreemptLowerPriority if value is unset in PriorityClass. This field is immutable. This field is available only when the PodGroupPreemptionPolicy feature gate is enabled.   Possible enum values:  - `\"Never\"` means that pod never preempts other pods with lower priority.  - `\"PreemptLowerPriority\"` means that pod can preempt other pods with lower priority.", alias="preemptionPolicy")
    priority: Optional[StrictInt] = Field(default=None, description="priority is the value of priority of this composite pod group. Various system components use this field to find the priority of the composite pod group. When Priority Admission Controller is enabled, it prevents users from setting this field. The admission controller populates this field from PriorityClassName. The higher the value, the higher the priority. This field is immutable.")
    priority_class_name: Optional[StrictStr] = Field(default=None, description="priorityClassName defines the priority that should be considered when scheduling this CompositePodGroup. Controllers are expected to fill this field by copying it from a CompositePodGroupTemplate. If left unspecified, it is validated and resolved similarly to the PriorityClassName field in Pods (i.e. if no priority class is specified, admission control can set this to the global default priority class if it exists. Otherwise, the composite pod group's priority will be zero). This field is immutable.", alias="priorityClassName")
    scheduling_constraints: Optional[IoK8sApiSchedulingV1alpha3CompositePodGroupSchedulingConstraints] = Field(default=None, description="schedulingConstraints defines optional scheduling constraints (e.g. topology) for this CompositePodGroup. Controllers are expected to fill this field by copying it from a CompositePodGroupTemplate. This field is immutable.", alias="schedulingConstraints")
    scheduling_policy: IoK8sApiSchedulingV1alpha3CompositePodGroupSchedulingPolicy = Field(description="schedulingPolicy defines the scheduling policy for this instance of the CompositePodGroup. Controllers are expected to fill this field by copying it from a CompositePodGroupTemplate. This field is immutable.", alias="schedulingPolicy")
    workload_ref: IoK8sApiSchedulingV1alpha3WorkloadReference = Field(description="workloadRef references an optional CompositePodGroup template within the Workload object that was used to create the CompositePodGroup. This field is required. This field is immutable.", alias="workloadRef")
    __properties: ClassVar[List[str]] = ["disruptionMode", "parentCompositePodGroupName", "preemptionPolicy", "priority", "priorityClassName", "schedulingConstraints", "schedulingPolicy", "workloadRef"]

    @field_validator('preemption_policy')
    def preemption_policy_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Never', 'PreemptLowerPriority']):
            raise ValueError("must be one of enum values ('Never', 'PreemptLowerPriority')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IoK8sApiSchedulingV1alpha3CompositePodGroupSpec from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of disruption_mode
        if self.disruption_mode:
            _dict['disruptionMode'] = self.disruption_mode.to_dict()
        # override the default output from pydantic by calling `to_dict()` of scheduling_constraints
        if self.scheduling_constraints:
            _dict['schedulingConstraints'] = self.scheduling_constraints.to_dict()
        # override the default output from pydantic by calling `to_dict()` of scheduling_policy
        if self.scheduling_policy:
            _dict['schedulingPolicy'] = self.scheduling_policy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of workload_ref
        if self.workload_ref:
            _dict['workloadRef'] = self.workload_ref.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IoK8sApiSchedulingV1alpha3CompositePodGroupSpec from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "disruptionMode": IoK8sApiSchedulingV1alpha3CompositeDisruptionMode.from_dict(obj["disruptionMode"]) if obj.get("disruptionMode") is not None else None,
            "parentCompositePodGroupName": obj.get("parentCompositePodGroupName"),
            "preemptionPolicy": obj.get("preemptionPolicy"),
            "priority": obj.get("priority"),
            "priorityClassName": obj.get("priorityClassName"),
            "schedulingConstraints": IoK8sApiSchedulingV1alpha3CompositePodGroupSchedulingConstraints.from_dict(obj["schedulingConstraints"]) if obj.get("schedulingConstraints") is not None else None,
            "schedulingPolicy": IoK8sApiSchedulingV1alpha3CompositePodGroupSchedulingPolicy.from_dict(obj["schedulingPolicy"]) if obj.get("schedulingPolicy") is not None else None,
            "workloadRef": IoK8sApiSchedulingV1alpha3WorkloadReference.from_dict(obj["workloadRef"]) if obj.get("workloadRef") is not None else None
        })
        return _obj


