# Copyright The Kubeflow Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# coding: utf-8

"""
    Kubeflow Trainer OpenAPI Spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: unversioned
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from kubeflow_trainer_api.models.io_k8s_api_core_v1_node_allocatable_mapped_resources import IoK8sApiCoreV1NodeAllocatableMappedResources
from kubeflow_trainer_api.models.io_k8s_api_core_v1_node_allocatable_overhead_resources import IoK8sApiCoreV1NodeAllocatableOverheadResources
from typing import Optional, Set
from typing_extensions import Self

class IoK8sApiCoreV1NodeAllocatableResourceClaimStatus(BaseModel):
    """
    NodeAllocatableResourceClaimStatus describes the status of node allocatable resources allocated via DRA.
    """ # noqa: E501
    containers: Optional[List[StrictStr]] = Field(default=None, description="Containers lists the names of all containers in this pod that reference the claim.")
    mapping: Optional[List[IoK8sApiCoreV1NodeAllocatableMappedResources]] = Field(default=None, description="Mapping contains allocations through devices mapped in the device spec's `nodeAllocatableResources[...].mapping` field. This is used by kubelet for pod level and container-level cgroup enforcement.")
    overhead: Optional[List[IoK8sApiCoreV1NodeAllocatableOverheadResources]] = Field(default=None, description="Overhead contains allocations through devices mapped in the device spec's `nodeAllocatableResources[...].overhead` field. This is used by kubelet for pod level and container-level cgroup enforcement.")
    resource_claim_name: StrictStr = Field(description="ResourceClaimName is the resource claim referenced by the pod that resulted in this node allocatable resource allocation.", alias="resourceClaimName")
    __properties: ClassVar[List[str]] = ["containers", "mapping", "overhead", "resourceClaimName"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IoK8sApiCoreV1NodeAllocatableResourceClaimStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in mapping (list)
        _items = []
        if self.mapping:
            for _item_mapping in self.mapping:
                if _item_mapping:
                    _items.append(_item_mapping.to_dict())
            _dict['mapping'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in overhead (list)
        _items = []
        if self.overhead:
            for _item_overhead in self.overhead:
                if _item_overhead:
                    _items.append(_item_overhead.to_dict())
            _dict['overhead'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IoK8sApiCoreV1NodeAllocatableResourceClaimStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "containers": obj.get("containers"),
            "mapping": [IoK8sApiCoreV1NodeAllocatableMappedResources.from_dict(_item) for _item in obj["mapping"]] if obj.get("mapping") is not None else None,
            "overhead": [IoK8sApiCoreV1NodeAllocatableOverheadResources.from_dict(_item) for _item in obj["overhead"]] if obj.get("overhead") is not None else None,
            "resourceClaimName": obj.get("resourceClaimName") if obj.get("resourceClaimName") is not None else ''
        })
        return _obj


