pull_request_rules:
  - name: Auto-merge lake-gate PRs to stable
    conditions:
      - base=stable
      - label=lake-gate
      - -draft
      - -closed
      - check-success~=^Red Hat Konflux.*
    actions:
      review:
        type: APPROVE
      merge:
        method: fast-forward
