pull_request_rules:
  - name: Auto-merge lake-gate PRs to stable
    conditions:
      - base=stable
      - label=lake-gate
      - -draft
      - -closed
      - check-success~=ok-to-test
    actions:
      merge:
        method: fast-forward
