/*
Copyright The Kubeflow Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apistrainerv1alpha1 "github.com/kubeflow/trainer/v2/pkg/apis/trainer/v1alpha1"
	versioned "github.com/kubeflow/trainer/v2/pkg/client/clientset/versioned"
	internalinterfaces "github.com/kubeflow/trainer/v2/pkg/client/informers/externalversions/internalinterfaces"
	trainerv1alpha1 "github.com/kubeflow/trainer/v2/pkg/client/listers/trainer/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterTrainingRuntimeInformer provides access to a shared informer and lister for
// ClusterTrainingRuntimes. Prefer using the type-safe variant (see [TypedClusterTrainingRuntimeInformer]).
type ClusterTrainingRuntimeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() trainerv1alpha1.ClusterTrainingRuntimeLister
}

// TypedClusterTrainingRuntimeInformer provides access to a shared informer and lister for
// ClusterTrainingRuntimes, including the type-safe TypedInformer variant.
// It is a superset of ClusterTrainingRuntimeInformer.
type TypedClusterTrainingRuntimeInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() ClusterTrainingRuntimeIndexInformer
	Lister() trainerv1alpha1.ClusterTrainingRuntimeLister
}

// ClusterTrainingRuntimeIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type ClusterTrainingRuntimeIndexInformer cache.TypedSharedIndexInformer[*apistrainerv1alpha1.ClusterTrainingRuntime]

// ClusterTrainingRuntimeHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for ClusterTrainingRuntime.
type ClusterTrainingRuntimeHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apistrainerv1alpha1.ClusterTrainingRuntime]

// ClusterTrainingRuntimeDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for ClusterTrainingRuntime.
type ClusterTrainingRuntimeDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apistrainerv1alpha1.ClusterTrainingRuntime]

// ClusterTrainingRuntimeFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for ClusterTrainingRuntime.
type ClusterTrainingRuntimeFilteringHandler = cache.TypedFilteringResourceEventHandler[*apistrainerv1alpha1.ClusterTrainingRuntime]

// ClusterTrainingRuntimeIndexers is a specialization of [cache.TypedIndexers] for ClusterTrainingRuntime.
type ClusterTrainingRuntimeIndexers = cache.TypedIndexers[*apistrainerv1alpha1.ClusterTrainingRuntime]

// DeletedClusterTrainingRuntime is a specialization of [cache.DeletedObject] for ClusterTrainingRuntime.
type DeletedClusterTrainingRuntime = cache.DeletedObject[*apistrainerv1alpha1.ClusterTrainingRuntime]

type clusterTrainingRuntimeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewClusterTrainingRuntimeInformer constructs a new informer for ClusterTrainingRuntime type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedClusterTrainingRuntimeInformer]).
func NewClusterTrainingRuntimeInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewClusterTrainingRuntimeInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedClusterTrainingRuntimeInformer constructs a new informer for ClusterTrainingRuntime type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedClusterTrainingRuntimeInformer(client versioned.Interface, resyncPeriod time.Duration, indexers ClusterTrainingRuntimeIndexers) ClusterTrainingRuntimeIndexInformer {
	return NewTypedClusterTrainingRuntimeInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredClusterTrainingRuntimeInformer constructs a new informer for ClusterTrainingRuntime type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredClusterTrainingRuntimeInformer]).
func NewFilteredClusterTrainingRuntimeInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedClusterTrainingRuntimeInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredClusterTrainingRuntimeInformer constructs a new informer for ClusterTrainingRuntime type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredClusterTrainingRuntimeInformer(client versioned.Interface, resyncPeriod time.Duration, indexers ClusterTrainingRuntimeIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) ClusterTrainingRuntimeIndexInformer {
	return NewTypedClusterTrainingRuntimeInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewClusterTrainingRuntimeInformerWithOptions constructs a new informer for ClusterTrainingRuntime type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedClusterTrainingRuntimeInformerWithOptions]).
func NewClusterTrainingRuntimeInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedClusterTrainingRuntimeInformerWithOptions(client, options)
}

// NewTypedClusterTrainingRuntimeInformerWithOptions constructs a new informer for ClusterTrainingRuntime type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedClusterTrainingRuntimeInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) ClusterTrainingRuntimeIndexInformer {
	gvr := schema.GroupVersionResource{Group: "trainer.kubeflow.org", Version: "v1alpha1", Resource: "clustertrainingruntimes"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apistrainerv1alpha1.ClusterTrainingRuntime](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.TrainerV1alpha1().ClusterTrainingRuntimes().List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.TrainerV1alpha1().ClusterTrainingRuntimes().Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.TrainerV1alpha1().ClusterTrainingRuntimes().List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.TrainerV1alpha1().ClusterTrainingRuntimes().Watch(ctx, opts)
			},
		}, client),
		&apistrainerv1alpha1.ClusterTrainingRuntime{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *clusterTrainingRuntimeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedClusterTrainingRuntimeInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *clusterTrainingRuntimeInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *clusterTrainingRuntimeInformer) TypedInformer() ClusterTrainingRuntimeIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apistrainerv1alpha1.ClusterTrainingRuntime](f.factory.InformerFor(&apistrainerv1alpha1.ClusterTrainingRuntime{}, f.defaultInformer))
}

func (f *clusterTrainingRuntimeInformer) Lister() trainerv1alpha1.ClusterTrainingRuntimeLister {
	return trainerv1alpha1.NewClusterTrainingRuntimeLister(f.Informer().GetIndexer())
}

// ToTypedClusterTrainingRuntimeInformer converts an untyped informer into a TypedClusterTrainingRuntimeInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *ClusterTrainingRuntime. If that is not the case, calling type-safe methods of the returned
// TypedClusterTrainingRuntimeInformer leads to runtime panics. A safer alternative is to pass
// around a TypedClusterTrainingRuntimeInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedClusterTrainingRuntimeInformer(informer ClusterTrainingRuntimeInformer) TypedClusterTrainingRuntimeInformer {
	if informer, ok := informer.(TypedClusterTrainingRuntimeInformer); ok {
		return informer
	}
	return &clusterTrainingRuntimeTypedInformerAdapter{informer}
}

type clusterTrainingRuntimeTypedInformerAdapter struct {
	ClusterTrainingRuntimeInformer
}

func (a *clusterTrainingRuntimeTypedInformerAdapter) TypedInformer() ClusterTrainingRuntimeIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apistrainerv1alpha1.ClusterTrainingRuntime](a.Informer())
}

// ToClusterTrainingRuntimeIndexInformer converts an untyped informer into a ClusterTrainingRuntimeIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *ClusterTrainingRuntime. If that is not the case, calling type-safe methods of the returned
// ClusterTrainingRuntimeIndexInformer leads to runtime panics. A safer alternative is to pass
// around a ClusterTrainingRuntimeIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToClusterTrainingRuntimeIndexInformer(informer cache.SharedIndexInformer) ClusterTrainingRuntimeIndexInformer {
	if informer, ok := informer.(ClusterTrainingRuntimeIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apistrainerv1alpha1.ClusterTrainingRuntime](informer)
}
