/*
Copyright The Kubeflow Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apistrainerv1alpha1 "github.com/kubeflow/trainer/v2/pkg/apis/trainer/v1alpha1"
	versioned "github.com/kubeflow/trainer/v2/pkg/client/clientset/versioned"
	internalinterfaces "github.com/kubeflow/trainer/v2/pkg/client/informers/externalversions/internalinterfaces"
	trainerv1alpha1 "github.com/kubeflow/trainer/v2/pkg/client/listers/trainer/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// TrainJobInformer provides access to a shared informer and lister for
// TrainJobs. Prefer using the type-safe variant (see [TypedTrainJobInformer]).
type TrainJobInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() trainerv1alpha1.TrainJobLister
}

// TypedTrainJobInformer provides access to a shared informer and lister for
// TrainJobs, including the type-safe TypedInformer variant.
// It is a superset of TrainJobInformer.
type TypedTrainJobInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() TrainJobIndexInformer
	Lister() trainerv1alpha1.TrainJobLister
}

// TrainJobIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type TrainJobIndexInformer cache.TypedSharedIndexInformer[*apistrainerv1alpha1.TrainJob]

// TrainJobHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for TrainJob.
type TrainJobHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apistrainerv1alpha1.TrainJob]

// TrainJobDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for TrainJob.
type TrainJobDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apistrainerv1alpha1.TrainJob]

// TrainJobFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for TrainJob.
type TrainJobFilteringHandler = cache.TypedFilteringResourceEventHandler[*apistrainerv1alpha1.TrainJob]

// TrainJobIndexers is a specialization of [cache.TypedIndexers] for TrainJob.
type TrainJobIndexers = cache.TypedIndexers[*apistrainerv1alpha1.TrainJob]

// DeletedTrainJob is a specialization of [cache.DeletedObject] for TrainJob.
type DeletedTrainJob = cache.DeletedObject[*apistrainerv1alpha1.TrainJob]

type trainJobInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewTrainJobInformer constructs a new informer for TrainJob type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedTrainJobInformer]).
func NewTrainJobInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewTrainJobInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedTrainJobInformer constructs a new informer for TrainJob type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedTrainJobInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers TrainJobIndexers) TrainJobIndexInformer {
	return NewTypedTrainJobInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredTrainJobInformer constructs a new informer for TrainJob type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredTrainJobInformer]).
func NewFilteredTrainJobInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedTrainJobInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredTrainJobInformer constructs a new informer for TrainJob type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredTrainJobInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers TrainJobIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) TrainJobIndexInformer {
	return NewTypedTrainJobInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewTrainJobInformerWithOptions constructs a new informer for TrainJob type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedTrainJobInformerWithOptions]).
func NewTrainJobInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedTrainJobInformerWithOptions(client, namespace, options)
}

// NewTypedTrainJobInformerWithOptions constructs a new informer for TrainJob type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedTrainJobInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) TrainJobIndexInformer {
	gvr := schema.GroupVersionResource{Group: "trainer.kubeflow.org", Version: "v1alpha1", Resource: "trainjobs"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apistrainerv1alpha1.TrainJob](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.TrainerV1alpha1().TrainJobs(namespace).List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.TrainerV1alpha1().TrainJobs(namespace).Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.TrainerV1alpha1().TrainJobs(namespace).List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.TrainerV1alpha1().TrainJobs(namespace).Watch(ctx, opts)
			},
		}, client),
		&apistrainerv1alpha1.TrainJob{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *trainJobInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedTrainJobInformerWithOptions(client, f.namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *trainJobInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *trainJobInformer) TypedInformer() TrainJobIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apistrainerv1alpha1.TrainJob](f.factory.InformerFor(&apistrainerv1alpha1.TrainJob{}, f.defaultInformer))
}

func (f *trainJobInformer) Lister() trainerv1alpha1.TrainJobLister {
	return trainerv1alpha1.NewTrainJobLister(f.Informer().GetIndexer())
}

// ToTypedTrainJobInformer converts an untyped informer into a TypedTrainJobInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *TrainJob. If that is not the case, calling type-safe methods of the returned
// TypedTrainJobInformer leads to runtime panics. A safer alternative is to pass
// around a TypedTrainJobInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedTrainJobInformer(informer TrainJobInformer) TypedTrainJobInformer {
	if informer, ok := informer.(TypedTrainJobInformer); ok {
		return informer
	}
	return &trainJobTypedInformerAdapter{informer}
}

type trainJobTypedInformerAdapter struct {
	TrainJobInformer
}

func (a *trainJobTypedInformerAdapter) TypedInformer() TrainJobIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apistrainerv1alpha1.TrainJob](a.Informer())
}

// ToTrainJobIndexInformer converts an untyped informer into a TrainJobIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *TrainJob. If that is not the case, calling type-safe methods of the returned
// TrainJobIndexInformer leads to runtime panics. A safer alternative is to pass
// around a TrainJobIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToTrainJobIndexInformer(informer cache.SharedIndexInformer) TrainJobIndexInformer {
	if informer, ok := informer.(TrainJobIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apistrainerv1alpha1.TrainJob](informer)
}
