/*
Copyright The Kubeflow Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apistrainerv1alpha1 "github.com/kubeflow/trainer/v2/pkg/apis/trainer/v1alpha1"
	versioned "github.com/kubeflow/trainer/v2/pkg/client/clientset/versioned"
	internalinterfaces "github.com/kubeflow/trainer/v2/pkg/client/informers/externalversions/internalinterfaces"
	trainerv1alpha1 "github.com/kubeflow/trainer/v2/pkg/client/listers/trainer/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// TrainingRuntimeInformer provides access to a shared informer and lister for
// TrainingRuntimes. Prefer using the type-safe variant (see [TypedTrainingRuntimeInformer]).
type TrainingRuntimeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() trainerv1alpha1.TrainingRuntimeLister
}

// TypedTrainingRuntimeInformer provides access to a shared informer and lister for
// TrainingRuntimes, including the type-safe TypedInformer variant.
// It is a superset of TrainingRuntimeInformer.
type TypedTrainingRuntimeInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() TrainingRuntimeIndexInformer
	Lister() trainerv1alpha1.TrainingRuntimeLister
}

// TrainingRuntimeIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type TrainingRuntimeIndexInformer cache.TypedSharedIndexInformer[*apistrainerv1alpha1.TrainingRuntime]

// TrainingRuntimeHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for TrainingRuntime.
type TrainingRuntimeHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apistrainerv1alpha1.TrainingRuntime]

// TrainingRuntimeDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for TrainingRuntime.
type TrainingRuntimeDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apistrainerv1alpha1.TrainingRuntime]

// TrainingRuntimeFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for TrainingRuntime.
type TrainingRuntimeFilteringHandler = cache.TypedFilteringResourceEventHandler[*apistrainerv1alpha1.TrainingRuntime]

// TrainingRuntimeIndexers is a specialization of [cache.TypedIndexers] for TrainingRuntime.
type TrainingRuntimeIndexers = cache.TypedIndexers[*apistrainerv1alpha1.TrainingRuntime]

// DeletedTrainingRuntime is a specialization of [cache.DeletedObject] for TrainingRuntime.
type DeletedTrainingRuntime = cache.DeletedObject[*apistrainerv1alpha1.TrainingRuntime]

type trainingRuntimeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewTrainingRuntimeInformer constructs a new informer for TrainingRuntime type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedTrainingRuntimeInformer]).
func NewTrainingRuntimeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewTrainingRuntimeInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedTrainingRuntimeInformer constructs a new informer for TrainingRuntime type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedTrainingRuntimeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers TrainingRuntimeIndexers) TrainingRuntimeIndexInformer {
	return NewTypedTrainingRuntimeInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredTrainingRuntimeInformer constructs a new informer for TrainingRuntime type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredTrainingRuntimeInformer]).
func NewFilteredTrainingRuntimeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedTrainingRuntimeInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredTrainingRuntimeInformer constructs a new informer for TrainingRuntime type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredTrainingRuntimeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers TrainingRuntimeIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) TrainingRuntimeIndexInformer {
	return NewTypedTrainingRuntimeInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewTrainingRuntimeInformerWithOptions constructs a new informer for TrainingRuntime type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedTrainingRuntimeInformerWithOptions]).
func NewTrainingRuntimeInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedTrainingRuntimeInformerWithOptions(client, namespace, options)
}

// NewTypedTrainingRuntimeInformerWithOptions constructs a new informer for TrainingRuntime type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedTrainingRuntimeInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) TrainingRuntimeIndexInformer {
	gvr := schema.GroupVersionResource{Group: "trainer.kubeflow.org", Version: "v1alpha1", Resource: "trainingruntimes"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apistrainerv1alpha1.TrainingRuntime](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.TrainerV1alpha1().TrainingRuntimes(namespace).List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.TrainerV1alpha1().TrainingRuntimes(namespace).Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.TrainerV1alpha1().TrainingRuntimes(namespace).List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.TrainerV1alpha1().TrainingRuntimes(namespace).Watch(ctx, opts)
			},
		}, client),
		&apistrainerv1alpha1.TrainingRuntime{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *trainingRuntimeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedTrainingRuntimeInformerWithOptions(client, f.namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *trainingRuntimeInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *trainingRuntimeInformer) TypedInformer() TrainingRuntimeIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apistrainerv1alpha1.TrainingRuntime](f.factory.InformerFor(&apistrainerv1alpha1.TrainingRuntime{}, f.defaultInformer))
}

func (f *trainingRuntimeInformer) Lister() trainerv1alpha1.TrainingRuntimeLister {
	return trainerv1alpha1.NewTrainingRuntimeLister(f.Informer().GetIndexer())
}

// ToTypedTrainingRuntimeInformer converts an untyped informer into a TypedTrainingRuntimeInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *TrainingRuntime. If that is not the case, calling type-safe methods of the returned
// TypedTrainingRuntimeInformer leads to runtime panics. A safer alternative is to pass
// around a TypedTrainingRuntimeInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedTrainingRuntimeInformer(informer TrainingRuntimeInformer) TypedTrainingRuntimeInformer {
	if informer, ok := informer.(TypedTrainingRuntimeInformer); ok {
		return informer
	}
	return &trainingRuntimeTypedInformerAdapter{informer}
}

type trainingRuntimeTypedInformerAdapter struct {
	TrainingRuntimeInformer
}

func (a *trainingRuntimeTypedInformerAdapter) TypedInformer() TrainingRuntimeIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apistrainerv1alpha1.TrainingRuntime](a.Informer())
}

// ToTrainingRuntimeIndexInformer converts an untyped informer into a TrainingRuntimeIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *TrainingRuntime. If that is not the case, calling type-safe methods of the returned
// TrainingRuntimeIndexInformer leads to runtime panics. A safer alternative is to pass
// around a TrainingRuntimeIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToTrainingRuntimeIndexInformer(informer cache.SharedIndexInformer) TrainingRuntimeIndexInformer {
	if informer, ok := informer.(TrainingRuntimeIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apistrainerv1alpha1.TrainingRuntime](informer)
}
