apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeflow-trainer-controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        ports:
        - containerPort: 8080
          name: metrics
